<?php

require_once '../config/database.php';

$database = new Database();
$db = $database->getConnection();

$month = $_GET['month'] ?? date('m');
$year  = $_GET['year'] ?? date('Y');

$totalOrders = $db->query("
    SELECT COUNT(*)
    FROM orders
    WHERE MONTH(created_at) = $month
    AND YEAR(created_at) = $year
")->fetchColumn();

$totalRevenue = $db->query("
    SELECT COALESCE(SUM(total),0)
    FROM orders
    WHERE MONTH(created_at) = $month
    AND YEAR(created_at) = $year
")->fetchColumn();

$totalProducts = $db->query("
    SELECT COALESCE(SUM(oi.quantity),0)
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.id
    WHERE MONTH(o.created_at) = $month
    AND YEAR(o.created_at) = $year
")->fetchColumn();

$bestSeller = $db->query("
    SELECT p.name
    FROM order_items oi
    JOIN products p ON oi.product_id = p.id
    JOIN orders o ON oi.order_id = o.id
    WHERE MONTH(o.created_at) = $month
    AND YEAR(o.created_at) = $year
    GROUP BY p.id
    ORDER BY SUM(oi.quantity) DESC
    LIMIT 1
")->fetchColumn();

$stmt = $db->query("
    SELECT
        p.name,
        p.category,
        SUM(oi.quantity) total_sold,
        SUM(oi.quantity * oi.price) revenue
    FROM order_items oi
    JOIN products p
        ON oi.product_id = p.id
    JOIN orders o
        ON oi.order_id = o.id
    WHERE MONTH(o.created_at) = $month
    AND YEAR(o.created_at) = $year
    GROUP BY p.id
    ORDER BY total_sold DESC
");

$data = $stmt->fetchAll(PDO::FETCH_ASSOC);

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=Domio-Sales-Report-$month-$year.xls");

?>

<html>

<head>
    <meta charset="UTF-8">
</head>

<body>

<table width="100%">

    <tr>

        <td colspan="5"
            align="center"
            style="
                font-size:22px;
                font-weight:bold;
                color:#543A14;
            ">

            DOMIO FURNITURE

        </td>

    </tr>

    <tr>

        <td colspan="5"
            align="center">

            E-Commerce Furniture Management System

        </td>

    </tr>

    <tr>

        <td colspan="5"
            align="center">

            Sales Performance Report

        </td>

    </tr>

</table>

<br>

<table border="1" cellpadding="8">

    <tr>

        <td colspan="2"
            style="
                background:#543A14;
                color:white;
                font-weight:bold;
            ">

            SALES SUMMARY

        </td>

    </tr>

    <tr>

        <td>
            Period
        </td>

        <td>
            <?= date('F', mktime(0,0,0,$month,1)); ?>
            <?= $year ?>
        </td>

    </tr>

    <tr>

        <td>
            Total Orders
        </td>

        <td>
            <?= $totalOrders ?>
        </td>

    </tr>

    <tr>

        <td>
            Products Sold
        </td>

        <td>
            <?= $totalProducts ?>
        </td>

    </tr>

    <tr>

        <td>
            Total Revenue
        </td>

        <td>
            Rp <?= number_format($totalRevenue,0,',','.') ?>
        </td>

    </tr>

    <tr>

        <td>
            Best Seller Product
        </td>

        <td>
            <?= $bestSeller ?>
        </td>

    </tr>

</table>

<br><br>

<table border="1" cellpadding="8">

    <tr
        style="
            background:#543A14;
            color:white;
            font-weight:bold;
        ">

        <th>No</th>
        <th>Product</th>
        <th>Category</th>
        <th>Qty Sold</th>
        <th>Revenue</th>

    </tr>

    <?php

    $no = 1;

    foreach($data as $row):

    ?>

    <tr>

        <td>
            <?= $no++; ?>
        </td>

        <td>
            <?= htmlspecialchars($row['name']); ?>
        </td>

        <td>
            <?= htmlspecialchars($row['category']); ?>
        </td>

        <td>
            <?= $row['total_sold']; ?>
        </td>

        <td>

            Rp <?= number_format(
                $row['revenue'],
                0,
                ',',
                '.'
            ); ?>

        </td>

    </tr>

    <?php endforeach; ?>

</table>

<br><br>

<table>

<tr>

<td>

Generated by Domio Admin System

</td>

</tr>

<tr>

<td>

Generated Date :
<?= date('d F Y H:i'); ?>

</td>

</tr>

</table>

</body>

</html>